#!/bin/bash
enp0s31f6=$(cat /sys/class/net/enp0s31f6/carrier 2>/dev/null)
wlp4s0=$(cat /sys/class/net/wlp4s0/carrier 2>/dev/null)

if [[ $enp0s31f6 -eq 1 ]]; then
    echo -e '\uf0ac'
elif [[ $wlp4s0 -eq 1 ]] && [[ $enp0s31f6 -ne 1 ]]; then
    echo -e '\uf1eb'
fi
