#!/bin/bash
# base panel script:
# https://github.com/baskerville/bspwm/blob/master/examples/panel/panel

cd $(dirname $0)
source $(dirname $)/config

#
# Main
#

if [[ $(pgrep -cx panel) -gt 1 ]]; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[[ -e $PANEL_FIFO ]] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding "$PANEL_HEIGHT"
bspc subscribe report > "$PANEL_FIFO" &

while true; do
    echo "S" \
        "${LIGHT_BLUE} $(./clock)  " \
        "$(./memory)  " \
        "$(./brightness)  " \
        "$(./volume)  " \
        "$(./battery)" \
        "$(./network)" \
        "$(./bluetooth-keyboard-connector)  " \
        "" > "$PANEL_FIFO"

	sleep 5s
done &

./panel_bar < "$PANEL_FIFO" | lemonbar -a 13 \
    -f "FontAwesome:size=10" \
    -f "Dejavu:size=9" \
     x"$PANEL_HEIGHT" \
    -F "$COLOUR_FOREGROUND" \
    -B "$COLOUR_BACKGROUND" \
    -g "$PANEL_GEOMETRY" | sh &

wait
# vim: set ft=sh:
