#! /usr/bin/zsh

sxhkd &


bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor eDP-1 -d $ws1 $ws2 $ws3 $ws4 $ws5
# bspc monitor HDMI-1 -d 6 7 8 9 0
bspc monitor eDP-1 -d WEB IDE VIM TTY0 TTY1
bspc monitor DP-3 -d 1 2 3 4 5

bspc wm eDP-1 DP-1


bspc config border_width         0
bspc config window_gap           1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Startup
# $HOME/.config/bspwm/panel/panel &

# setting background image
# feh --bg-fill ~/.yondonjamts/bruno-aguirre.jpg
# feh --bg-fill ~/.yondonjamts/yawn.jpg
# feh --bg-fill ~/.yondonjamts/city.png
feh --bg-fill ~/.yondonjamts/mountain.jpg
